### ISSUE TITLE
Geogebra

### ISSUE THREAD

**Issue by yasim-doner** [Yahya-Asim-DONER-9-E/9Sinif-3Odev#1]
![Grafik Çizen Hesap Makinesi - GeoGebra - Opera 18 04 2020 12_41_14 (2)](https://user-images.githubusercontent.com/63353356/79634342-86708f80-8172-11ea-9e11-ee6702a31b0b.png)

**Comment by ofenerci** [comment]
Yahya sen aşmışsın!

**Comment by ofenerci** [comment]
Yahya 3.soruya nasıl fikrim yok dersin! İlk 2 bölümü harika yapmışsın. Bir fikrin olsun.

**Comment by yasim-doner** [comment]
Hocam 3. bölümde is kinetik enerji teoremini biliyodum fakat ordan sürtünmeyi naıl bulacağımızı yapamamıştım attığınız örnek üzerinden anladım ama

**Comment by Yahya-Asim-DONER-9-E** [comment]
Hocam bide biz bunları yapıyoruz ama doğru cevaplarınıda sonradan atsanız bizde kontrol etsek daha iyi olur gibi
